/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculator_CONSTANTS_H
#define calculator_CONSTANTS_H

#include "calculator_types.h"

namespace calculator {

class calculatorConstants {
 public:
  calculatorConstants();

  int32_t WINDOW_WIDTH;
  int32_t WINDOW_HEIGHT;
  int32_t BUTTON_SIZE_X;
  int32_t BUTTON_SIZE_Y;
};

extern const calculatorConstants g_calculator_constants;

} // namespace

#endif
