/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculator_constants.h"

namespace calculator {

const calculatorConstants g_calculator_constants;

calculatorConstants::calculatorConstants() {
  WINDOW_WIDTH = 320;

  WINDOW_HEIGHT = 416;

  BUTTON_SIZE_X = 48;

  BUTTON_SIZE_Y = 48;

}

} // namespace

